name:                awesome
version:             0.1.0.0
github:              "gribouille/awesome"
license:             MPL-2.0 
author:              "gribouille"
maintainer:          "gribouille.git@gmail.com"
copyright:           "2019 Gribouille <gribouille.git@gmail.com>"

extra-source-files:
- README.md
- LICENSE

data-files:
- assets/star.png
- assets/license.png

description: Please see the README on GitHub at <https://github.com/gribouille/awesome#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14
- directory >= 1.3 && < 2
- aeson >= 1.4 && < 2
- bytestring >= 0.10
- req >= 1.2 && < 2
- http-client >= 0.5
- text >= 1.2 && < 2
- transformers >= 0.3
- data-default
- split >= 0.2
- async >= 2.2
- pretty-terminal >= 0.1
- time >= 1.8 && < 2
- text-format >= 0.3
- filepath >= 1.4

library:
  source-dirs: src
  exposed-modules:
    - Awesome

executables:
  awesome:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - awesome

